server {
    listen       80;
    server_name  localhost;

    # Serve the front end and static files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

	# Mandatory headers for Godot Web Exports
        add_header 'Cross-Origin-Opener-Policy' 'same-origin';
        add_header 'Cross-Origin-Embedder-Policy' 'require-corp';

    # API endpoint to dynamically retrieve the list of game directories
    location /api/games_list/ {
        alias /usr/share/nginx/html/;
        index _non_existent_file_;
        autoindex on;
        autoindex_format json;
    }
}
