services:
  game-site:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME:-mygames-site}
    restart: unless-stopped
    volumes:
      # Map your local games folder to the Nginx web root
      - ./games:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${PORT:-8081}:80"   # LAN-only; firewall if needed
    networks:
      - homelab-gateway
      - homelab



networks:
  homelab-gateway:
    external: true
  homelab:
    external: true
